# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
# ===================================================================

logging:
    level:
        ROOT: DEBUG
        com.eagro: DEBUG
        io.github.jhipster: DEBUG

spring:
    profiles:
        active: dev
        include: swagger
 
    jpa:
      #database: POSTGRESQL
      show-sql: true
      hibernate:
        properties:
          hibernate:
            format_sql: true
        ddl-auto: none
    #datasource:
      #platform: postgres
      #url: jdbc:postgresql://localhost:5433/postgres
      #username: postgres
      #password: admin
      #driverClassName: org.postgresql.Driver
      
   
    h2:
        console:
            enabled: true

server:
    port: 8080

